[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
skip-string-normalization = true
exclude = '''
(
  /(
    \.git
    | \.tox
    | \.venv
    | migrations
    | settings
  )
)
'''